### ISSUE TITLE
Request for new ontology Radiation Therapy Ontology

### ISSUE THREAD

**Issue by jonathanbona** [OBOFoundry/OBOFoundry.github.io#2683]
### Title

Radiation Therapy Ontology

### Short Description

An ontology describing the domain of radiation therapy concerned primarily with the processes and equipment used to deliver therapeutic radiation in a clinical setting.

### Description

An ontology describing the domain of radiation therapy concerned primarily with the processes and equipment used to deliver therapeutic radiation in a clinical setting. RTO aims to be useful in bridging institutional and clinical practice differences. It is also intended to useful in investigations in oncology which includes medical, surgical and genetic oncological domains.  In modeling this domain, RTO uses terms from many existing OBO ontologies, including the Chemical entities of Biological Interest; Ontology for General Medical Science; Ontology for Biomedical Investigations; and more.

### Identifier Space

RTO

### License

CC-BY 4.0

### Domain

health

### Source Code Repository

https://github.com/aapm-bdsc-ontology-tg/rto

### Homepage

https://github.com/aapm-bdsc-ontology-tg/rto

### Issue Tracker

https://github.com/aapm-bdsc-ontology-tg/rto/issues

### Contribution Guidelines

https://github.com/aapm-bdsc-ontology-tg/rto/blob/main/CONTRIBUTING.md

### Ontology Download Link

https://github.com/aapm-bdsc-ontology-tg/rto/blob/main/rto.owl

### Contact Name

Jonathan Bona

### Contact Email

jonathanbona@gmail.com

### Contact GitHub Username

jonathanbona

### Contact ORCID Identifier

https://orcid.org/0000-0003-1402-9616

### Formats

- [x] OWL RDF/XML (.owl)
- [x] OBO (.obo)
- [ ] OBO Graph JSON (.json)

### Dependencies

- bfo
- cob
- chebi
- doid
- iao
- obi
- ogms
- pato
- rbo
- ro

### Usages

```yaml

```

### OBO Foundry Pre-registration Checklist

- [x] I have read and understood [the registration process instructions](http://obofoundry.org/docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html) and the [registration checklist](https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md).
- [x] There is no other ontology in the OBO Foundry which would be an appropriate place for my terms. If there were, I have contacted the editors, and we decided in mutual agreement that a separate ontology is more appropriate.
- [x] My ontology has a specific release file with a version IRI and a `dc:license` annotation, serialised in RDF/XML.
- [x] My identifiers (classes and properties IRIs) are formatted according to the [OBO Foundry Identifier Policy](http://obofoundry.org/id-policy)
- [x] My term labels are in English and conform to the OBO Foundry [Naming Conventions](http://obofoundry.org/principles/fp-012-naming-conventions.html)
- [x] I understand that term definitions are key to understanding the intentions of a term, especially when the ontology is used in curation. I made sure that a reasonable majority of terms in my ontology--and all top level terms--have definitions, in English, using the [IAO:0000115](https://ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115) property.
- [x] For every term in my ontology, I checked whether another OBO Foundry ontology has one with the same meaning. If so, I re-used that term directly (not by cross-reference, by directly using the IRI).
- [x] For all relationship properties (Object and Data Property), I checked whether [the Relation Ontology (RO)](https://ontobee.org/ontology/catalog/RO?iri=http://www.w3.org/2002/07/owl%23ObjectProperty) includes an appropriate one. I understand that aligning with RO is an essential part of the overall alignment between OBO ontologies!
- [x] For the selection of appropriate annotation properties, I looked at [OMO](https://ontobee.org/ontology/catalog/OMO?iri=http://www.w3.org/2002/07/owl%23AnnotationProperty) first. I understand that aligning ontology metadata and term-level metadata is essential for cross-integration of OBO ontologies.
- [x] If I was not sure about the meaning of any of the checkboxes above, I have consulted with a member of the OBO Foundry for advice, e.g., through the [obo-discuss](https://groups.google.com/g/obo-discuss) Google Group.
- [x] The requested ID space does not conflict with another ID space found in other registries such as the Bioregistry and BioPortal, see [here](https://obofoundry.org/id-policy) for a complete list.

**Comment by cmungall** [comment]
Links don't resolve - perhaps you accidentally made the repos private?

**Comment by jonathanbona** [comment]
> Links don't resolve - perhaps you accidentally made the repos private?

Fixed, thanks!

**Comment by pfabry** [comment]
Dear @jonathanbona ,

Thank you for your submission. The review will be executed as a two stage process:

First, you will have to pass [OBO NOR Dashboard](https://obofoundry.org/obo-nor.github.io/dashboard/index.html). Pass means that no check apart from Users and Versioning may be red. In addition, a new check is currently implemented: it consists in a lexical match of your original terms with those already existing in OBO Foundry published ontologies. The goal is to prevent the duplication of terms with similar meanings (cf. [Review SOP](http://obofoundry.org/docs/SOP.html#ROOM)). A list of terms that are potential duplicates will be provided soon.

After you have successfully passed the Dashboard you will be assigned an OBO Operations committee member to review the ontology. The assigned reviewer is to be considered the final arbiter of requirements; look to that reviewer's guidance regarding which suggestions made by other reviewers must be done, which suggestions are simply good to do but not required, and which should not be done.

Usually, the review will result in an opportunity for you to improve the ontology. When the reviewer believes the ontology is ready for presentation to the OBO Operations Committee, they will present your ontology during an OBO Operations Call. This gives other members of the committee the opportunity to assess your work.

When a decision is reached by the committee you will be informed here on the issue tracker. The process can take any number of weeks or months, depending on the case at hand.
Please let us know about any reasons you might have for increased urgency.

You will be informed once your ontology is loaded in the OBO NOR Dashboard.

Good luck!

**Comment by pfabry** [comment]
Dear @jonathanbona 
Your ontology has been added to the [OBO NOR Dashboard](https://obofoundry.org/obo-nor.github.io/dashboard/index.html).
The lexmatch results are available here: [RTO lexmatch 20250228.txt](https://github.com/user-attachments/files/19029181/RTO.lexmatch.20250228.txt)
All terms IRI must follow the OBO Foundry format (cf. [Principle 3](http://obofoundry.org/principles/fp-003-uris.html)).

**Comment by jonathanbona** [comment]
Thank you @pfabry. We haven't included OBO Foundry style IRIs yet because we did not want to presume that we would receive the requested namespace. Is this something we could change after a namespace is granted?

**Comment by pfabry** [comment]
Dear @jonathanbona,

Following [Principle #3](https://obofoundry.org/principles/fp-003-uris.html), a namespace should be in place at the time of submission, even if the IRI does not resolve. However, this can be adjusted during the review process. Since this was the only technical issue, a reviewer will be assigned soon.

**Comment by shawntanzk** [comment]
Hi all, thanks for submitting your ontology to OBO foundry and trusting me with the review process. Please see my comments below, I hope they are helpful and please feel free to ping me for any clarifications needed - I will follow this issue :) 

# Review of RTO

I have almost no knowledge of the field, and my approach to reviewing is one coming from a naïve angle, so I do ask for your patience and understanding in this review - I am looking at it more for the lens of what I know and might question things based on my ignorance of the domain. 

## Ontology Scope

RTO describes the domain of radiation therapy with focus on processes and equipment used to delivery radiation in a clinical setting. 

I would like to understand the use case of RTO as there are ontologies for medical action like MAXO that do already contain radiation therapy http://purl.obolibrary.org/obo/MAXO_0000014, however I do understand that RTO also takes from different areas and joins them up. Having the purpose added to the description would therefore help users (and me) understand what the purpose of the ontology is. 

## Prefix

As mentioned in previous comment, submission should conform to OBO foundry identifier policy. 

## Imported terms

There seems to be some import files that bring in non native terms (eg obi_import.txt bringing in BFO, IAO, PATO terms), I would recommend instead directly importing from source ontologies (which also is brought in). 

There is also an odd case where alpha decay is under RTO namespace but beta decay is under RBO namespace, and on that note, why is beta decay is declared in the ontology rather than imported from RBO?  

There is also overlaps with RBO (eg radiation source). Not saying that that is wrong as there might be reasons for replicate where modelling choices are not in agreement and the application of this requires certain modelling choices, but would like to have a reason. 

## Relationships 

Generally terms do not have relationship to each other, I don't know the field enough to properly comment on this, but would like to understand the reason for the lack of axioms aside from parent relationship. For example, could there be relationships between the RTO classes under directive information entity? 

Planning target volume should have axioms 'has_part some "clinical target volume"' and 'has_part some "gross tumor volume"' by the definition.  

## Single individual Amersham 6702

I do not have knowledge of the field so I cannot comment on the modelling here, however I am curious as to why there is only one type of radiation source (again it might be my lack of domain knowledge).

**Comment by nlharris** [comment]
@jonathanbona have you had a chance to look at the reviewers' helpful comments on your ontology and work on resolving them?

**Comment by jonathanbona** [comment]
@nlharris yes, thank you for checking in. We are working on addressing these. What is the next step when we have completed revisions to the ontology and a written response to all points raised in the review? Should we post a response in this thread with a link to a new release of the ontology?

**Comment by nlharris** [comment]
Yes! Thanks!
